### ISSUE TITLE
Reemplazar informe red de expertos (excel) por pdf sólo con los controles revisados

### ISSUE THREAD

**Issue by trschober** [e-gob/pmg-seguridad#8]
El informe en Excel que se genera para cada servicio no tiene tanto valor puesto que se presta para confusión (¿qué control me revisaron, por qué aparecen los 114?)
Para eliminar esta confusión y simplificar la información entregada a los servicios, podríamos emitir un PDF que contenga solamente los controles que fueron revisados por la red y la observación general.

Conversemos para definir diseño del pdf

**Comment by manuelmunoz00** [comment]
excel con solo lo que revise la red de expertos.
